# -*- coding: utf-8 -*-

"""
SwarmDigiz Auto Campaign Engine

This engine evaluates leads generated by the Visual Inspector
and automatically suggests marketing campaigns.
"""

import json


# ---------------------------------------------------------
# Lead → Campaign Trigger
# ---------------------------------------------------------

def evaluate_auto_campaign(result: dict):

    lead_score = result.get("lead_score", 0)

    campaigns = []

    # HIGH VALUE LEAD
    if lead_score >= 70:

        campaigns.append(
            {
                "type": "google_search",
                "objective": "Lead Generation",
                "suggested_budget": 300,
                "headline": "Book Your Service Today",
                "description": "Limited time service discounts available.",
            }
        )

        campaigns.append(
            {
                "type": "facebook_lead",
                "objective": "Lead Generation",
                "suggested_budget": 200,
                "headline": "Schedule Your Inspection Today",
                "description": "Fast, affordable service near you.",
            }
        )

    # MEDIUM LEAD
    elif lead_score >= 40:

        campaigns.append(
            {
                "type": "facebook_retarg",
                "objective": "Retargeting",
                "suggested_budget": 100,
                "headline": "Still Need Service?",
                "description": "Complete your booking today.",
            }
        )

    return campaigns


# ---------------------------------------------------------
# Campaign Display Helper
# ---------------------------------------------------------

def format_campaigns_for_ui(campaigns):

    formatted = []

    for c in campaigns:

        formatted.append(
            {
                "platform": c["type"],
                "objective": c["objective"],
                "budget": c["suggested_budget"],
                "headline": c["headline"],
                "description": c["description"],
            }
        )

    return formatted