import uuid
from datetime import datetime


def generate_booking_id() -> str:
    """
    Generate a short booking identifier.
    """
    return uuid.uuid4().hex[:8]


def create_booking(username: str, quote: dict, appointment_time) -> dict:
    """
    Creates a booking record based on quote data.

    Parameters
    ----------
    username : str
        The user/customer making the booking

    quote : dict
        Quote object generated by the quote engine

    appointment_time : datetime | str
        Selected appointment time

    Returns
    -------
    dict
        Booking record
    """

    if not username:
        raise ValueError("Username is required for booking")

    if not quote:
        raise ValueError("Quote data is required to create booking")

    # Convert appointment_time safely
    if isinstance(appointment_time, datetime):
        appointment_time = appointment_time.isoformat()

    booking = {
        "booking_id": generate_booking_id(),
        "customer": username,
        "quote_price": quote.get("quote_price", 0),
        "discount": quote.get("discount_applied", 0),
        "upsell": quote.get("upsell_offer"),
        "urgency": quote.get("urgency", "normal"),
        "appointment_time": appointment_time,
        "status": "scheduled",
        "created_at": datetime.utcnow().isoformat()
    }

    return booking