# -*- coding: utf-8 -*-

"""
SwarmDigiz Automated Marketing Swarm

Automatically launches marketing campaigns for
high value leads generated by the Visual Inspector.

This engine:
1. Evaluates whether the swarm should trigger
2. Determines marketing strategy using AI lead prediction
3. Generates AI campaign assets
4. Launches campaigns across supported platforms
5. Prevents duplicate campaign execution using Automation Guard
"""

from core.ai_campaign_generator import generate_ai_campaign_assets
from core.campaign_launch_engine import launch_full_campaign
from core.lead_prediction_engine import predict_lead_outcome
from core.automation_guard import allow


# ---------------------------------------------------------
# Swarm Trigger Evaluation
# ---------------------------------------------------------

def evaluate_swarm_trigger(result):

    lead_score = result.get("lead_score", 0)
    lead_tier = result.get("lead_tier", "cold")

    # Trigger swarm for strong leads
    if lead_score >= 70 or lead_tier == "hot":
        return True

    return False


# ---------------------------------------------------------
# Determine Marketing Strategy
# ---------------------------------------------------------

def determine_swarm_strategy(result):

    prediction = predict_lead_outcome(result)

    tier = prediction.get("prediction_tier")

    if tier == "High Probability":
        strategy = "booking_priority"

    elif tier == "Medium Probability":
        strategy = "remarketing"

    else:
        strategy = "discount_campaign"

    return strategy, prediction


# ---------------------------------------------------------
# Run Marketing Swarm
# ---------------------------------------------------------

def run_marketing_swarm(result):

    # Identify customer for automation guard
    customer = result.get("customer", {})

    identifier = (
        customer.get("email")
        or customer.get("phone")
        or customer.get("name")
        or "unknown"
    )

    # -----------------------------------------------------
    # Automation Guard
    # -----------------------------------------------------

    if not allow("campaign", identifier):

        return {
            "status": "blocked",
            "reason": "automation guard prevented duplicate campaign"
        }

    # -----------------------------------------------------
    # Prevent double execution in same pipeline run
    # -----------------------------------------------------

    if result.get("swarm_executed"):
        return {
            "status": "already_executed",
            "reason": "swarm already ran for this inspection"
        }

    # -----------------------------------------------------
    # Evaluate trigger
    # -----------------------------------------------------

    if not evaluate_swarm_trigger(result):
        return {
            "status": "no_campaign_triggered",
            "reason": "lead score too low"
        }

    # -----------------------------------------------------
    # Determine AI strategy
    # -----------------------------------------------------

    strategy, prediction = determine_swarm_strategy(result)

    # -----------------------------------------------------
    # Generate AI campaign assets
    # -----------------------------------------------------

    assets = generate_ai_campaign_assets(result)

    # -----------------------------------------------------
    # Launch campaigns
    # -----------------------------------------------------

    launch_results = launch_full_campaign(assets)

    # Mark swarm execution
    result["swarm_executed"] = True

    return {
        "status": "campaign_launched",
        "strategy": strategy,
        "prediction": prediction,
        "assets": assets,
        "launch_results": launch_results
    }